services:
  postgres_db:
    container_name: postgres_db_container
    image: postgres:14
    restart: always
    env_file: .env 
    
    environment: 
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    
    volumes:
      - pg_db_vol:/var/lib/postgresql/data
    networks:
      - mydjangocomposenetwork

  web_services:
    container_name: django_compose_container
    image: employee_web_services:latest
    build: .
    command: >
      sh -c "python manage.py migrate --noinput &&
      python manage.py collectstatic --noinput &&
      python manage.py runserver 0.0.0.0:8000"

    # command: >
    # sh -c "python manage.py makemigrations &&
    #       python manage.py migrate --noinput &&
    #       python manage.py runserver 0.0.0.0:8000"

    restart: always
    depends_on:
      - postgres_db

    ports: 
      - "${DJANGO_LOCAL_PORT}:${DJANGO_DOCKER_PORT}"

    environment: 
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    
    volumes:
      - django_app_vol:/app
      - ./static:/app/static  # Add this if you have static files
      - ./templates:/app/templates  # Add this if you have custom templates
    
    networks:
      - mydjangocomposenetwork

volumes:
  pg_db_vol:
  django_app_vol:

networks:
  mydjangocomposenetwork: