compose_file: docker-compose.yml
project_name: employee
docker_image: "thapavishal/employee"
env_file: .env
app_port: 8000

# --- RDatabase Variables for env.j2 Template ---
DB_NAME: employeecrud_db      # <-- FIX: Defines the missing variable
DB_USER: postgres
DB_PASSWORD: 1996
DB_HOST: postgres_db          # This is the Docker service name
DB_PORT: 5432




# Purpose:
# Defines production-specific environment variables.